export const ADD_NEWPERSON = "ADD_NEWPERSON";
export const FETCH_PERSONS_FULFILLED = "FETCH_PERSONS_FULFILLED";
export const FETCH_PERSON_REJECTED = "FETCH_PERSON_REJECTED";
export const SAVE_PERSON_FULFILLED = "SAVE_PERSON_FULFILLED";
export const SAVE_PERSON_REJECTED = "SAVE_PERSON_REJECTED";
export const FETCH_PERSON_FULFILLED = "FETCH_PERSON_FULFILLED";
export const UPDATE_PERSON_FULFILLED = "UPDATE_PERSON_FULFILLED";
export const UPDATE_PERSON_REJECTED = "UPDATE_PERSON_REJECTED";
export const DELETE_PERSON_FULFILLED = "DELETE_PERSON_FULFILLED";

